@startuml
'https://plantuml.com/class-diagram

+class InventoryManagementApplication{
+void start(Stage primaryStage)
+void main(String[] args)
}

+class InventoryItem{
-String name
-String value
-String serialNumber
+InventoryItem(String name, String value, String )
+String toString()
+void setDescription(String description)
+void setDueDate(String dueDate)
+void setCompleted(boolean completed)
+String getDescription()
+String getDueDate()
+boolean getCompleted()
+{static} List<Item> getToDoList()
+{static} void removeFromList(Item item)
}

+class InventoryController{
-TextField descriptionField
-CheckBox doneCheckBoxChecked
-TextField dueDateField
-Label infoLabel
-CheckBox showCompletedCheckBox
-CheckBox showIncompleteCheckBox
-TableColumn<Item, Boolean> doneView
-TableColumn<Item, String> dueDateView
-TableColumn<Item, String> taskView
-TableView<Item, String> listView
-int index
void initialize()
void addItemButtonClicked(ActionEvent event)
void clearListButtonClicked(ActionEvent event)
void exportButtonClicked(ActionEvent event)
+void exportToDoList(File selectedFile)
void importButtonClicked(ActionEvent event)
+void importToDoList(File selectedFile)
void removeItemButtonClicked(ActionEvent event)
void showDoneChecked(ActionEvent event)
void showNotDoneChecked(ActionEvent event)
+void populateCompleteOrIncompleteList(boolean completed)
-void uncheck()
-void clear()
-void displayItem()
+void createItem()
+void addItemToList(String description, String dueDate, boolean isChecked)
-void addAndDisplayItem(String description, String dueDate, boolean completed)
-void validateDuplicates()
+void removeItemFromList()
}

+class InventoryList{

}


InventoryManagementApplication -- InventoryController
InventoryController --* InventoryItem
InventoryController --* InventoryList
InventoryItem --* InventoryList


@enduml