@startuml
'https://plantuml.com/class-diagram

+class InventoryManagementApplication{
+void start(Stage primaryStage)
+void main(String[] args)
}

+class InventoryItem{
-String name
-String value
-String serialNumber
+InventoryItem(String name, String value, String serialNumber)
+String getName()
+String getValue()
+String getSerialNumber()
+boolean setName(String name)
+boolean setValue(String value)
+boolean setSerialNumber(String serialNumber)
+{static} boolean nameIsValid(String name)
+{static} boolean valueIsValid(String value)
+{static} boolean serialNumberIsValid(String serialNumber)
-{static} String removeDollarSign(String value)
}

+class InventoryController{
-TableView<InventoryItem> inventoryView
-TableColumn<InventoryItem, String> itemNameView
-TableColumn<InventoryItem, String> valueView
-TableColumn<InventoryItem, String> serialNumView
-TextField nameField
-TextField valueField
-TextField serialField
-TextField searchBar
-RadioButton byNameButton
-CheckBox clearCheckBox
-Label infoLabel
-InventoryList inventory
-int index
-{static} String FILE_NOT_FOUND_MESSAGE
-{static}  String FILE_WROTE_MESSAGE
-{static} String IMPORT_SUCCESSFUL_MESSAGE

void initialize()
void addItemButtonClicked(ActionEvent event)
String addItemToInventory(String projectedName, String projectedValue, String projectedSerialNumber)
-void displayItem()
boolean serialIsNotDuplicate(String serialNumber)
void clearTextFields()
void removeItemButtonClicked(ActionEvent event)
void clearListButtonClicked(ActionEvent event)
void exportButtonClicked(ActionEvent event)
String determineType(File file)
void exportTSV(File file)
void exportHTML(File file)
void exportJSON(File file)
void importButtonClicked(ActionEvent event)
void importInventoryFromTSV(File file)
void importInventoryFromHTML(File file)
void importInventoryFromJSON(File file)
void searchButtonClicked(ActionEvent event)
ObservableList displaySearchedItems(String searchString, boolean searchingByName)

}

+class InventoryList{
- ObservableList<InventoryItem> inventory
+boolean addItem(String name, String value, String serialNumber)
+void removeItem(InventoryItem item)
+void clearList()
+ObservableList<InventoryItem> getInventory()
}


InventoryManagementApplication -- InventoryController
InventoryController --* InventoryItem
InventoryController --* InventoryList
InventoryItem --* InventoryList


@enduml